pipeline {
    agent any

    environment {
        REGISTRY = "salimanaim123"
        IMAGE = "securedev-app"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                bat "docker build -t %REGISTRY%/%IMAGE%:latest app"
            }
        }

        stage('Generate SBOM') {
            steps {
                echo 'Generating SBOM with Syft...'
                bat "scripts\\generate_sbom.bat"
            }
        }

        stage('Scan SBOM (Grype)') {
            steps {
                echo 'Scanning SBOM with Grype...'
                bat "scripts\\grype_scan.bat"
            }
        }

        stage('Scan Docker Image (Trivy)') {
            steps {
                echo 'Scanning Docker image with Trivy...'
                bat "scripts\\trivy_scan.bat %REGISTRY%/%IMAGE%:latest"
            }
        }

        stage('Archive Reports') {
            steps {
                archiveArtifacts artifacts: '*.json, *.txt', allowEmptyArchive: true
            }
        }

        stage('Fail on Critical Vulns') {
            steps {
                script {
                    def critical = bat(
                        script: 'findstr /C:"CRITICAL" grype-report.txt',
                        returnStatus: true
                    )
                    if (critical == 0) {
                        error("❌ Vulnérabilités CRITIQUES détectées")
                    }
                }
            }
        }

        stage('Sign Image (Cosign)') {
            steps {
                withCredentials([file(credentialsId: 'cosign.key', variable: 'COSIGN_KEY')]) {
                    bat "scripts\\sign.bat %REGISTRY%/%IMAGE%:latest"
                }
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([string(credentialsId: 'registry_token', variable: 'REG_TOKEN')]) {
                    bat "docker login -u %REGISTRY% -p %REG_TOKEN%"
                    bat "docker push %REGISTRY%/%IMAGE%:latest"
                }
            }
        }
    }

    post {
        success {
            echo '✅ Secure DevSecOps pipeline completed successfully'
        }
        failure {
            echo '❌ Secure DevSecOps pipeline failed'
        }
    }
}
