@Library('jenkins-shared') _
pipeline {
    agent any

    environment {
        REGISTRY = "salimanaim123"
        IMAGE = "securedev-app"
    }

    stages {

        // ------------------- Checkout GitHub -------------------
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        // ------------------- Build Docker Image -------------------
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                bat "docker build -t %REGISTRY%/%IMAGE%:latest app"
            }
        }

        // ------------------- Push Docker Image -------------------
        stage('Push Image') {
            steps {
                withCredentials([string(credentialsId: 'registry_token', variable: 'REG_TOKEN')]) {
                    echo 'Pushing Docker image to Docker Hub...'
                    bat "docker login -u %REGISTRY% -p %REG_TOKEN%"
                      // bat "docker push docker.io/forbiddenuser/securepipeline:latest"
                   bat "docker push %REGISTRY%/%IMAGE%:latest"
                }
            }
        }

        // ------------------- Generate SBOM -------------------
        stage('Generate SBOM') {
            steps {
                echo 'Generating SBOM with Syft...'
                bat "scripts\\generate_sbom.bat"
            }
        }

        // ------------------- Scan SBOM (Grype) -------------------
        stage('Scan SBOM') {
            steps {
                echo 'Scanning SBOM with Grype...'
                bat "scripts\\grype_scan.bat"
            }
        }

        // ------------------- Scan Docker Image (Trivy) -------------------
        stage('Scan Image') {
            steps {
                echo 'Scanning Docker image with Trivy...'
                bat "scripts\\trivy_scan.bat %REGISTRY%/%IMAGE%:latest"
            }
        }

        // ------------------- Archive Reports -------------------
        stage('Archive Reports') {
            steps {
                echo 'Archiving SBOM and scan reports...'
                archiveArtifacts artifacts: '*.json, *.txt', allowEmptyArchive: true
            }
        }

        // ------------------- Fail on Critical Vulnerabilities -------------------
        stage('Fail on Critical Vulns') {
            steps {
                script {
                    def critical = bat(
                        script: 'findstr /C:"CRITICAL" grype-report.txt',
                        returnStatus: true
                    )
                    echo "High vulnerabilities found status: ${critical}"
                    if (critical == 0) {
                        error("❌ Vulnérabilités CRITIQUES détectées !")
                    }
                }
            }
        }

        // ------------------- Sign Docker Image -------------------
 stage('Sign Image (Cosign)') {
    steps {
        withCredentials([
            file(credentialsId: 'cosign.key', variable: 'COSIGN_KEY'),
            string(credentialsId: 'cosign_password', variable: 'COSIGN_PASSWORD'),
            string(credentialsId: 'registry_token', variable: 'REG_TOKEN')
        ]) {
            echo 'Signing Docker image with Cosign...'
            bat "scripts\\sign.bat %COSIGN_KEY% %REGISTRY%/%IMAGE%:latest %REG_TOKEN%"
        }
    }
}

    }

    post {
        success {
            echo '✅ Secure DevSecOps pipeline completed successfully'
        }
        failure {
            echo '❌ Secure DevSecOps pipeline failed'
        }
         always {
            // Appel à ta Shared Library pour notifier Spring Boot
            notifySpringBoot()
        }
    }
}
